---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: if-not-exists
  image: plugins/git
  settings:
    depath: 50
    tags: true

- name: front
  pull: if-not-exists
  image: node:18.12.0
  commands:
  - npm install
  - npm run build
  - npm run serve
  when:
    branch:
    - master
    - dev